repos:
  # Frontend formatting with Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|scss|md|html)$
        args: [--config, frontend/.prettierrc]
        additional_dependencies:
          - prettier@3.5.3

  # Backend formatting and linting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      # Run the linter
      - id: ruff
        files: ^backend/.*\.py$
        args: [--fix]
      # Run the formatter
      - id: ruff-format
        files: ^backend/.*\.py$

  # General hooks for both projects
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=5000]
      - id: check-merge-conflict
